services:
  - type: web
    name: mahzarbashi-telegram-bot-v2
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
