services:
  - type: web
    name: mahzarbashi-telegram-bot
    env: python
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8249435097:AAEqSwTL8Ah8Kfyzo9Z_iQE97OVUViXtOmY
