services:
  - type: web
    name: mahzarbashi-telegram-bot-v3
    env: python
    plan: free
    buildCommand: ""
    startCommand: >
      bash -c "
      python set_webhook.py &&
      uvicorn main:app --host 0.0.0.0 --port 10000
      "
    envVars:
      - key: BOT_TOKEN
        sync: false
