services:
  - type: web
    name: mahzarbashi-telegram-bot-v2
    env: python
    plan: free
    buildCommand: ""
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        sync: false
